server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: ms-usuarios
  datasource:
    url: jdbc:postgresql://${DB_USUARIOS_HOST:localhost}:${DB_USUARIOS_PORT:5432}/${DB_USUARIOS_NAME:ms_usuarios}
    username: ${DB_USUARIOS_USER:usuarios_user}
    password: ${DB_USUARIOS_PASSWORD:usuarios_pass}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
