server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: ms-users
  datasource:
    url: jdbc:postgresql://${DB_USERS_HOST:localhost}:${DB_USERS_PORT:5432}/${DB_USERS_NAME:ms_users}
    username: ${DB_USERS_USER:ms_users_app}
    password: ${DB_USERS_PASSWORD:ms_users_pass}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${MS_SECURITY_JWKS_URI:http://localhost:8082/.well-known/jwks.json}

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  cors:
    allowed-origin: ${APP_VAADIN_ORIGIN:http://localhost:8080}
